### ISSUE TITLE
Commit history

### ISSUE THREAD

**Issue by elifoster** [CurseStaff/GitSplit#1]
Will this program automatically recreate commit history related to the project being removed in its new repository? I'm not really sure how this would even be done logically, but I figure'd I'd might as well ask.

**Comment by cpaul747** [comment]
The new repo will contain a history of only the commits that affected the configured directories and files.  It will omit the commits that would not have a change within the scope of the new project, and stitch the parents of the commits back together without any reference to the omitted one. Commits with branches and tags that would be created are always preserved.  I think I added an option to retain all commits even if they don't apply, or if not it would be a simple change to add it.

**Comment by elifoster** [comment]
Awesome, that is exactly what I asked and exactly how I hoped it worked. Ive never even read c# code so figuring out how it works by reading it wasn't really an option. Thanks, closing!

**Comment by cpaul747** [comment]
I just wanted to make a clarification - This does not remove the project from the source repo.  It creates a new repo that never had it, leaving the source repo untouched, so its different than using filter-branch in that regard.  If you want to split a repo, you take one source repo, and output two new repos.  If you want to overwrite the source repo (after storing a backup!) you have to do that yourself.  Since it's entirely safe to run, you can look at the output repo and iterate on it to get your config right.
